services:
  qa-telegram-bot:
    build:
      context: .
      dockerfile: dockerfile-qa-tg-bot
    container_name: "qa-telegram-bot"
    image: "qa-telegram-bot:latest"
    networks:
      - qa-telegram-bot-net
    restart: unless-stopped

  qa-tg-bot-interface-back:
    build:
      context: .
      dockerfile: dockerfile-qa-tg-bot-back
    container_name: "qa-tg-bot-interface-back"
    image: qa-tg-bot-interface-back:latest
    networks:
      - qa-telegram-bot-net
    restart: unless-stopped

  qa-tg-bot-interface-front:
    build:
      context: .
      dockerfile: dockerfile-qa-tg-bot-front
    container_name: "qa-tg-bot-interface-front"
    image: "qa-tg-bot-interface-front:latest"
    networks:
      - qa-telegram-bot-net
    restart: unless-stopped
  
  # nginx-qa-tg-bot:
  #   image: nginx:latest
  #   container_name: "nginx-qa-tg-bot"
  #   ports:
  #     - '11798:11798'
  #   networks:
  #     - qa-telegram-bot-net
  #   volumes:
  #     #- "./src/nginxConfigs/nginx.conf:/etc/nginx/nginx.conf"
  #     - "./src/nginxConfigs/sslCert/:/etc/nginx/sslCert/"
  #     - "./src/nginxConfigs/conf.d/:/etc/nginx/conf.d/"
  #   restart: unless-stopped